export const DOCUMENT: any = {
  id: 'DOCUMENT-ID',
  createdAt: 1656466269000,
  isDeleted: false,
  length: 0,
  isHidden: false,
  linkPermission: 'READ',
  myPermissionRole: 'OWNER',
  name: 'Document Name',
  channelId: '9efa06bf-30de-4300-b71e-c04f46af8987',
  preview: undefined,
  thumbnailUrl: undefined,
  updatedAt: 1657001478000,
  userId: 'User Id',
  viewCount: 105,
  workspaceId: 'workspace-id',
};

export const MY_SELF: any = {
  connectionId: 320,
  userId: 'USER-ID',
  username: 'USER-NAME',
  color: '#A74C65',
  isRecord: false,
  isPresenter: 0,
  followTarget: '',
};

export const OTHERS: any[] = [
  {
    connectionId: 322,
    userId: 'userId-1',
    username: 'username-1',
    color: '#8B8E94',
    isRecord: false,
    isPresenter: 0,
    followTarget: '',
  },
  {
    connectionId: 324,
    userId: 'userId-2',
    username: 'username-2',
    color: '#CBC4B2',
    isRecord: false,
    isPresenter: 0,
    followTarget: '',
  },
  {
    connectionId: 325,
    userId: 'userId-3',
    username: 'username-3',
    color: '#3B73F1',
    isRecord: false,
    isPresenter: 0,
    followTarget: '',
  },
  {
    connectionId: 326,
    userId: 'userId-4',
    username: 'username-4',
    color: '#000000',
    isRecord: false,
    isPresenter: 0,
    followTarget: '',
  },
  {
    connectionId: 328,
    userId: 'userId-5',
    username: 'username-5',
    color: '#FF823A',
    isRecord: false,
    isPresenter: 0,
    followTarget: '',
  },
];
